"""add role_title location salary to generated_cover_letter

Revision ID: 2c4571a050e3
Revises: 33c54260d07a
Create Date: 2026-03-21 17:22:46.344962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c4571a050e3'
down_revision: Union[str, Sequence[str], None] = '33c54260d07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_cover_letter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('salary', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_cover_letter', schema=None) as batch_op:
        batch_op.drop_column('salary')
        batch_op.drop_column('location')
        batch_op.drop_column('role_title')

    # ### end Alembic commands ###
