"""add location salary job_description to application

Revision ID: 33c54260d07a
Revises: b79c1cca3379
Create Date: 2026-03-21 15:53:31.641447

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "33c54260d07a"
down_revision: str | Sequence[str] | None = "b79c1cca3379"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.add_column(sa.Column("location", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("salary", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("job_description", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application", schema=None) as batch_op:
        batch_op.drop_column("job_description")
        batch_op.drop_column("salary")
        batch_op.drop_column("location")

    # ### end Alembic commands ###
