"""smart_url_cover_letter_columns

Revision ID: 3ff3cb29e1fa
Revises: d89ac2dc3096
Create Date: 2026-03-17 22:38:50.461889

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ff3cb29e1fa"
down_revision: str | Sequence[str] | None = "d89ac2dc3096"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "generated_cover_letter", sa.Column("job_url", sa.String(), nullable=True)
    )
    op.add_column(
        "generated_cover_letter", sa.Column("match_score", sa.Integer(), nullable=True)
    )
    op.add_column(
        "generated_cover_letter", sa.Column("fit_analysis", sa.Text(), nullable=True)
    )
    op.add_column(
        "generated_cover_letter",
        sa.Column("tone", sa.String(), nullable=False, server_default="professional"),
    )
    op.add_column(
        "generated_cover_letter",
        sa.Column("application_status", sa.String(), nullable=True, server_default=None),
    )
    op.add_column(
        "generated_cv", sa.Column("application_status", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("generated_cv", "application_status")
    op.drop_column("generated_cover_letter", "application_status")
    op.drop_column("generated_cover_letter", "tone")
    op.drop_column("generated_cover_letter", "fit_analysis")
    op.drop_column("generated_cover_letter", "match_score")
    op.drop_column("generated_cover_letter", "job_url")
    # ### end Alembic commands ###
