"""add multi profile support

Revision ID: 574a3faf36f1
Revises: 62ecad596d28
Create Date: 2026-03-15 17:54:25.625734

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "574a3faf36f1"
down_revision: str | Sequence[str] | None = "62ecad596d28"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("generated_cover_letter", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_generated_cover_letter_profile_id_profile",
            "profile",
            ["profile_id"],
            ["id"],
        )

    with op.batch_alter_table("generated_cv", schema=None) as batch_op:
        batch_op.add_column(sa.Column("profile_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_generated_cv_profile_id_profile", "profile", ["profile_id"], ["id"]
        )

    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("label", sa.String(), nullable=False, server_default="Default")
        )
        batch_op.add_column(
            sa.Column("color", sa.String(), nullable=False, server_default="#6366f1")
        )
        batch_op.add_column(
            sa.Column("icon", sa.String(), nullable=False, server_default="💼")
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("profile", schema=None) as batch_op:
        batch_op.drop_column("icon")
        batch_op.drop_column("color")
        batch_op.drop_column("label")

    with op.batch_alter_table("generated_cv", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("profile_id")

    with op.batch_alter_table("generated_cover_letter", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("profile_id")
    # ### end Alembic commands ###
