"""add_application_tracker

Revision ID: b79c1cca3379
Revises: 3ff3cb29e1fa
Create Date: 2026-03-17 22:59:02.252395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79c1cca3379'
down_revision: Union[str, Sequence[str], None] = '3ff3cb29e1fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role_title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('job_url', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('generated_cover_letter', sa.Column('application_id', sa.Integer(), nullable=True))
    with op.batch_alter_table('generated_cover_letter', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_generated_cover_letter_profile_id_profile'), type_='foreignkey')
        batch_op.create_foreign_key('fk_generated_cover_letter_application_id_application', 'application', ['application_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_generated_cover_letter_profile_id_profile', 'profile', ['profile_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('generated_cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('application_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_generated_cv_profile_id_profile'), type_='foreignkey')
        batch_op.create_foreign_key('fk_generated_cv_application_id_application', 'application', ['application_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_generated_cv_profile_id_profile', 'profile', ['profile_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('generated_cv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_generated_cv_profile_id_profile'), 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('application_id')

    with op.batch_alter_table('generated_cover_letter', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_generated_cover_letter_profile_id_profile'), 'profile', ['profile_id'], ['id'])
        batch_op.drop_column('application_id')

    op.drop_table('application')
    # ### end Alembic commands ###
